---
title: "Lightening Round Essays"
format: html
editor: visual
---

**Answer each of the following questions with *one sentence* including a brief explanation.**

1.  Finish the sentence with another student’s name:

    "If Connie Xian doesn’t earn an A, then nobody should, because whenever I 
    was stuck I turned to them for help and they could always clearly explain 
    their code and the reasoning behind every step."

2.  What was the most difficult part of the class for you? List a general topic, a specific problem, a kind of work we did, etc. and explain why.

    The most difficult part of the class for me was keeping track of all the 
    different R libraries and functions, because I often mixed up similar 
    functions (like read.csv() vs read_csv() or levels() vs fct_levels()). I 
    think this primarily happened because I would refer to papers and chat 
    that would use different packages for the same method, or R will 
    autofill/suggest wrong functions.

3.  What was the easiest part of the class for you? Explain why.

    The easiest part of the class for me was the in class practice assignments 
    with the “coder” and “computer” roles, because that structure made it clear 
    who should talk, who should type, and helped me understand the code better 
    by explaining it out loud or carefully listening.

4.  What part of the class surprised or interested you the most? Explain why.

    The part of the class that surprised and interested me the most was the 
    weekly pair programming, because switching between coder and computer 
    roles showed me how differently people think about R code and pushed me to 
    explain my ideas out loud.

5.  Give one piece of advice to a student just beginning a quarter of STAT 331 that will help them be successful in learning.

    My advice to a new STAT 331 student is to really lean into the tidyverse 
    style from the beginning use pipes, keep your code organized and commented, 
    and take pair programming and peer feedback seriously because talking 
    through your code with others will make everything click much faster.
